---
- hosts: all
  become: true

  tasks:
    - name: Install tmux
      apt: 
        name: "{{item}}"
      loop:
        - tmux
        - r-base-core 
        - gcc
        - git
        - python3

    - name: Create App repo
      shell: |
        mkdir -p /app/R /app/hadoop

    - git: 
        repo: https://github.com/Maissacrement/RFastBuild.git
        dest: /app/R

    - git:
        repo: https://github.com/apache/hadoop.git
        dest: /app/hadoop
